name: Feature Branch Checks
on:
  pull_request:
    branches: [ "dev" ]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
      packages: read
      actions: read
    container:
      image: ghcr.io/giotto-suite/ci-giottosuite/ci-env
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags
      - name: catch R deps not in container
        run: devtools::install_deps()
        shell: Rscript {0}
      - name: Build and install
        run: |
          R CMD build .
          R CMD INSTALL *.tar.gz
      - name: Set RETICULATE_PYTHON environment variable
        run: |
          echo "RETICULATE_PYTHON=/opt/miniconda/envs/r-reticulate/bin/python" >> $GITHUB_ENV
        shell: bash
      - name: Run tests
        run: |
          library(testthat)
          library(GiottoUtils)
          test_dir("tests/testthat")
        shell: Rscript {0}
